FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend-admin/package*.json ./
RUN npm install

COPY frontend-admin/ .
COPY shared/ /shared

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend-admin/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3002

CMD ["nginx", "-g", "daemon off;"]
